version: '3.9'

services:
  app:
    image: server
    container_name: server
    depends_on:
      - postgres-db
    networks:
      - ps
  postgres-db: 
    image: postgres:latest
    container_name: rest_api_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: rest_api_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5430:5432"
    restart: unless-stopped
    networks:
      - ps

networks:
  ps:
